%define _source_filedigest_algorithm    md5
%define _binary_filedigest_algorithm    md5

%define debug_package %nil

Summary: Prerequisites, Packages, Services, Sanity check tools
Name: ppsst
Version: 1.0.8
Release: 1SSE
Group: Application/System
Source: %{name}-%{version}.tgz
License: LANL
BuildRoot: %{_tmppath}/%{name}-%{version}-root
BuildArch: noarch
Requires: bash, yum, chkconfig, coreutils, lsof
Packager: Ben McClelland <ben@lanl.gov>, Andrew Shewmaker <shewa@lanl.gov>, Daryl W. Grunau <dwg@lanl.gov>

%description
install prerequisite directories, files, and packages (minimum needed to install via yum, basically)
install/remove packages (or groups) via yum
enable/disable services on/off
perform a sanity check of the installation (looks for files uncontrolled by RPM or cfengine database)

%package buildroot
Summary: root image scripts for ppsst
Group: Application/System
Requires: hybridize >= 1.0-3
%description buildroot
root image scripts for ppsst

%prep
%setup -q

# I want everything non-writable since we're carrying around RCS
# revisions.
find . -not -type d -exec chmod u-w {} \;

%build

%install
%{__rm} -rf %{buildroot}
%{__mkdir_p} %{buildroot}%{_sysconfdir}/profile.d
%{__mkdir_p} %{buildroot}%{_sysconfdir}/sysconfig
%{__mkdir_p} %{buildroot}/opt/%{name}/bin
%{__mkdir_p} %{buildroot}/opt/%{name}/etc/downgrade
%{__mkdir_p} %{buildroot}/var/cache/%{name}

%{__install} -p -m755 ./%{_sysconfdir}/profile.d/%{name}.sh %{buildroot}%{_sysconfdir}/profile.d/%{name}.sh
%{__install} -p -m755 ./%{_sysconfdir}/sysconfig/%{name} %{buildroot}%{_sysconfdir}/sysconfig/%{name}

# executables
for i in \
  build \
  chroot_cmd \
  createimg \
  hierarchical_sync \
  packages \
  prereqs \
  rpm_cmd \
  sanity \
  services \
  yum_cmd
do
  %{__install} -p -m755 opt/%{name}/bin/$i %{buildroot}/opt/%{name}/bin/$i
done

# configs
for i in \
  installgroups \
  installpackages \
  onservices \
  removegroups \
  removepackages \
  excludepackages
do
  %{__install} -p -m644 opt/%{name}/etc/$i %{buildroot}/opt/%{name}/etc/$i
done

# doc
%{__mkdir_p} -m 755 $RPM_BUILD_ROOT%{_mandir}/man1
%{__install} -p -m 0444 ./%{_mandir}/man1/ppsst.1 $RPM_BUILD_ROOT%{_mandir}/man1/ppsst.1

%clean
%{__rm} -rf %{buildroot}

%post

# In order to avoid doing damage to a running system, put all of the services 
# that are currently chkconfiged on into the onservices config file
echo -e "#\n# This file is automatically generated by PPSST post install\n#" > /opt/%{name}/etc/onservices
if [ -e "/usr/bin/systemd" ]; then
  /usr/bin/systemctl -t service --full --no-legend | %{__awk} -F '.service' '{print $1}' | /usr/bin/sort >> /opt/%{name}/etc/onservices
else
  /sbin/chkconfig --list 2>&1 | %{__grep} -E "[1-5]:on|[[:space:]]on" | %{__perl} -ne '/^\s*([^:\s]+)[:\s]/ && print "$1\n"' >> /opt/%{name}/etc/onservices
fi

%files
%defattr(-,root,root)
%{_sysconfdir}/profile.d/%{name}.sh
%config(noreplace) %{_sysconfdir}/sysconfig/%{name}
%attr(0755,root,root) /opt/%{name}/bin/build
%attr(0755,root,root) /opt/%{name}/bin/chroot_cmd
%attr(0755,root,root) /opt/%{name}/bin/packages
%attr(0755,root,root) /opt/%{name}/bin/prereqs
%attr(0755,root,root) /opt/%{name}/bin/rpm_cmd
%attr(0755,root,root) /opt/%{name}/bin/sanity
%attr(0755,root,root) /opt/%{name}/bin/services
%attr(0755,root,root) /opt/%{name}/bin/yum_cmd
%config(noreplace) /opt/%{name}/etc
%attr(0755,root,root) /var/cache/%{name}
%doc %{_mandir}/man1/ppsst.1*

%files buildroot
%defattr(-,root,root)
%attr(0755,root,root) /opt/%{name}/bin/createimg
%attr(0755,root,root) /opt/%{name}/bin/hierarchical_sync

%changelog
* Tue Oct 1 2013 Ben McClelland <ben@lanl.gov> 1.0.8-1SSE
- add downgrade directory to rpm
- add hybridize options to createimg

* Fri Jul 12 2013 Ben McClelland <ben@lanl.gov> 1.0.7-2SSE
- enable downgrade directory instead of just reporting

* Thu Jun 6 2013 Ben McClelland <ben@lanl.gov> 1.0.7-1SSE
- finalize version for FC18 with bugfixes
- rootfs: use chkconfig & systemd to find onservices
- add downgrade directory capability

* Tue May 28 2013 Ben McClelland <ben@lanl.gov> 1.0.6-6SSE
- services rewrite for better integration with systemd and chkconfig systems
- added set -x for debug
- check for pre-req package exist before install

* Mon May 13 2013 Ben McClelland <ben@lanl.gov> 1.0.6-5SSE
- remove verbose debugging messages without debug flag

* Mon May 13 2013 Ben McClelland <ben@lanl.gov> 1.0.6-4SSE
- fixup post process to generate onservices

* Mon May 13 2013 Ben McClelland <ben@lanl.gov> 1.0.6-2SSE
- bugfixes for systemd
- trim mdmonitor-takeover.service from list because it doesnt work correectly

* Mon May 13 2013 Ben McClelland <ben@lanl.gov> 1.0.6-1SSE
- systemd integration

* Mon May 06 2013 Daryl W. Grunau <dwg@lanl.gov> 1.0.5-11SSE
- BUGFIX (packages): handle the case where excludepackages and removepackages
  files exist and are specified, however the total content of both files is
  empty (excluding comments).

* Wed May 01 2013 Daryl W. Grunau <dwg@lanl.gov> 1.0.5-10SSE
- (createimg): relocate the KERNEL assignment after hybridize to pick up the
  kernel flagged by hybridize; require perceus-hybridize >= 1.0-3.  Resolve
  broken symlinks in the weak-updates by copying the data, rather than just deleting.
- (packages): mount proc onto VNFS images read-only.  Terminate processes that
  become co-dependent on the VNFS root as packages are installed (rogue %post
  scripts?) so that proc can be cleanly unmounted every time; require lsof.

* Tue Oct 23 2012 Daryl W. Grunau <dwg@lanl.gov> 1.0.5-9SSE
- BUGFIX (yum_cmd): send STDERR to /dev/null instead of closing the FH.

* Thu Oct 18 2012 Daryl W. Grunau <dwg@lanl.gov> 1.0.5-8SSE
- (build): IMG = `hostname -s` for the execution host.

* Thu Oct 18 2012 Daryl W. Grunau <dwg@lanl.gov> 1.0.5-7SSE
- Output prefix ppsst: -> ppsst[$IMG]:

* Wed Oct 17 2012 Daryl W. Grunau <dwg@lanl.gov> 1.0.5-6SSE
- (createimg): fixup weak-updates by iterating through existent directories.
- (packages): cleanup *.rpmorig, *.rpmsave and *.rpmnew in vnfs images.
- (yum_cmd): show 'missing requires'.

* Tue Oct 16 2012 Daryl W. Grunau <dwg@lanl.gov> 1.0.5-5SSE
- BUGFIX (yum_cmd): $img assignment s.b. based on the ROOT env variable,
  not CFGDIR.

* Tue Oct 16 2012 Daryl W. Grunau <dwg@lanl.gov> 1.0.5-4SSE
- More pretty printing.

* Tue Aug 28 2012 Daryl W. Grunau <dwg@lanl.gov> 1.0.5-3SSE
- Pretty-print the yum command based on the number of arguments
  given to that command.

* Tue Aug 28 2012 Daryl W. Grunau <dwg@lanl.gov> 1.0.5-2SSE
- Enhancement (yum_cmd): show 'Cleanup' messages from yum install/update.

* Tue Aug 28 2012 Daryl W. Grunau <dwg@lanl.gov> 1.0.5-1SSE
- BUGFIX (yum_cmd): ENV variable legend; assert the existence/validity of
  YUMCFG and ROOT.  Make STDERR and STDOUT unbuffered in exec'd children.

* Fri Aug 24 2012 Daryl W. Grunau <dwg@lanl.gov> 1.0.4-1SSE
- BUGFIX: foreach -> while to get "live" data on the output stream, in
  yum_cmd.

* Fri Aug 24 2012 Daryl W. Grunau <dwg@lanl.gov> 1.0.3-1SSE
- BUGFIX: don't destroy @ARGV with the print function in yum_cmd!

* Fri Aug 24 2012 Daryl W. Grunau <dwg@lanl.gov> 1.0.2-1SSE
- Perlify the yum_cmd to make it do what we want
- Disable 'xargs --verbose' when VERBOSE is requested
- When VERBOSE, send yum-complete-transaction STDERR to /dev/null

* Wed Aug 22 2012 Daryl W. Grunau <dwg@lanl.gov> 1.0.1-1SSE
- BUGFIX: fixups to rpmlist(), rpmlist_csv() and rpmlist_escglob()
  to protect whitespace in list entries (usu. RPM names do not
  contain spaces but Group names may).
- BUGFIX: permit comments trailing a service name in the onservices file.
- BUGFIX: fixups to specfile post to properly handle xinetd services.

* Wed Jun 20 2012 Daryl W. Grunau <dwg@lanl.gov> 1.0.0-1SSE
- Generate a "universal" {S}RPM that can be built on/for any platform by
  setting the _source_filedigest_algorithm and _binary_filedigest_algorithm
  to the lowest common denominator (md5).
- BUGFIX: services::print_servicenames() does not match all valid service
  names so patch up the perlre.

* Mon May 07 2012 Daryl W. Grunau <dwg@lanl.gov> 0.8.3-3SSE
- Apply similar yum_cmd patch to host yum installs too.
- Only touch $CFGDIR/.createimg for alternate root builds.

* Mon May 07 2012 Daryl W. Grunau <dwg@lanl.gov> 0.8.3-2SSE
- BUGFIX: undo parts of previous yum_cmd verbosity reporting patch.

* Thu May 03 2012 Daryl W. Grunau <dwg@lanl.gov> 0.8.3-1SSE
- Andrew's parting-patch rollup:
  o   echo "DRYRUN=$DRYRUN" if DEBUG
  o   remove broken symlinks in vnfs:/lib/modules/* and re-depmod
  o   check for YUM updates
      finish previous YUM transactions
      addn'l YUM cache cleanup
  o   better yum_cmd verbosity reporting

* Wed Feb 22 2012 Andrew Shewmaker <shewa@lanl.gov>
- 0.8.2
- createimg - TMPDIR/CWD error
- hierarchical_sync - only activate with command line flag (now documented)

* Fri Jan 13 2012 Andrew Shewmaker <shewa@lanl.gov>
- 0.8.1
- packages - don't exit in cleanup unless it's a trap
- createimg - syntax error

* Thu Jan 12 2012 Andrew Shewmaker <shewa@lanl.gov>
- 0.8
- packages - add trap so that things like the proc mount are cleaned up correctly
-          - allow inline comments in any config file
- createimg - check for mounts in the rootfs, unmount, and check again before continuing
- services - allow inline comments in any config file

* Tue Dec 7 2011 Andrew Shewmaker <shewa@lanl.gov>
- 0.7
- man page
- build no longer checks for newer files -- leaves it up to cfengine or the person executing
- build order of -r and -c args no longer matter
- build lockfile contains pid and script looks for a running process before deciding to quit
- build -- hierarchical_sync is now a nondefault option (-s)
- hierarchical_sync was missing critical quotes (patch from Daryl)
- createimg now errors out immediately if the image has no kernel installed
- createimg now leaves .createimg during a dryrun
- packages and services now only count lines in config files that are not comments, empty, or whitespace

* Wed Nov 9 2011 Andrew Shewmaker <shewa@lanl.gov>
- 0.6
- split perceus functionality and dependencies into subpackage
-
- build script:
-  running host should assume /etc/yum.conf location
-  no md5s ... it turns out to be a pain in practice
-  fix to -f (force) option
-
- perceus script:
-  change name to createimg (perceus conflicts with actual perceus command)
-  embed the createimg script ... that way we don't have the same one with each image
-
- hierarchical_sync script:
-  use full path when checking for pexec
-  PARALLELISM var set in sysconfig for pexec
-
- packages script:
-  md5s are a pain in practice
-  when checking for equality to zero, use the arithmetic operator instead of string
-
- services script:
-  xinetd.d typo fix
-  use arithmetic ops instead of strings when dealing with zero
-
- yum_cmd script:
-  need to see a few more messages from yum (errors, conflicts, etc.)

* Fri Oct 21 2011 Andrew Shewmaker <shewa@lanl.gov>
- fixed bug in hierarchical_sync default var
- replace zzz kludge in package script
- reformat missing service errors
- format dryrun messages to make it obvious nothing is being done
- fix build script so tha find -newer isn't sometimes missing an arg
- use md5 to be smarter about running subparts

* Thu Oct 20 2011 Andrew Shewmaker <shewa@lanl.gov>
- added post install script to populate onservices with current setup of the system
- split out hierarchical boot sync support from perceus

* Wed Oct 19 2011 Andrew Shewmaker <shewa@lanl.gov>
- corrected permissions
- added config directives where appropriate
- services fixes (check for empty, put sane default in config file, start according to runlevel, etc.)
- only create vmlinuz symlink if necessary
- other little fixes

* Thu Oct 13 2011 Andrew Shewmaker <shewa@lanl.gov>
- refactored build script
- chose to call the collection Prereqs, Packages, Services, Sanity Tools (PPSST)

* Mon Aug 23 2011 Ben McClelland <ben@lanl.gov>
- First cut.
